### ISSUE TITLE
Show Tabs in Magit and Eshell

### ISSUE THREAD

**Issue by jasonmj** [ema2159/centaur-tabs#100]
Perhaps I'm missing something obvious, but I can't seem to get the tabs to show in either Magit or Eshell. 

I have centaur-tabs-hide-tabs-hooks set to nil.

**Comment by ema2159** [comment]
With Magit (and probably eshell although I'm not that sure) it happens because it's buffers use the headerline, which is where the tabs are displayed. I'm working on displaying them in the tab line for Emacs 27, but for other versions I think it's not possible.

**Comment by jasonmj** [comment]
Interestingly, if I toggle `centaur-tabs-local-mode` on then to off while in magit mode, the tabs work as I would like them to.

**Comment by ema2159** [comment]
Yes, that's because after you execute that command, the `centaur-tabs` format overrides the `header-line-format` that's used by Magit. You could try to add a hook with centaur-tabs-local-mode for Magit but I'm not that sure if that would work.

**Comment by ema2159** [comment]
I managed to make it work for Emacs 27 with native tab-line. I managed to make it work for term-mode, ansi-term-mode and eshell-mode. For some reason in most Magit buffers works (i.e. Magit log) but for magit-status-mode it just doesn't and I don't know why. For terminal emulators it should be working on Emacs 26 but for Magit because it uses the heder-line, it will only work for Emacs 27.

**Comment by jasonmj** [comment]
I also got it working by adding this to my config:
`(defun toggle-centaur-tabs-local-mode()
  (interactive)
  (call-interactively 'centaur-tabs-local-mode)
  (call-interactively 'centaur-tabs-local-mode))
(add-hook 'magit-status-mode-hook 'toggle-centaur-tabs-local-mode)`

**Comment by ema2159** [comment]
Well, that also works! It's a little bit forced but fir this case it's ok
