### ISSUE TITLE
Centaur-tabs-set-bar position options?

### ISSUE THREAD

**Issue by ianpan870102** [ema2159/centaur-tabs#14]
Many modern editors/IDEs like to have the selected tab indicator to be at the bottom or top of the tab (instead of the left). Is there any plan to implement this option?

P.s. Love this package, well done mate!

**Comment by ema2159** [comment]
Hi! That's a feature I'm planning to add, it's right there in the TO DO list. Actually its really, really easy to implement without the icons (just adding a `(when centaur-tabs-set-overline ... (:overline t))`. The problem is that all-the-icons is a really troublesome package that when you look it with a bad eye it magically stops working. I'll figure it out when I get a little bit more of time!

**Comment by ema2159** [comment]
> P.s. Love this package, well done mate!

Thanks! I really really like working on this so if you can recommend it to other users I really would appreciate it!

**Comment by ianpan870102** [comment]
> The problem is that all-the-icons is a really troublesome package that...
That sounds unfortunate, in the meanwhile I'll wait patiently for this feature.

> if you can recommend it to other users I really would appreciate it!
Absolutely, I really hope this package gets popular. At the end of the day, people still care about the UI/UX and I'm very glad that you are changing this in Emacs for the better.

**Comment by ema2159** [comment]
How about this?
![DeepinScreenshot_select-area_20190710152936](https://user-images.githubusercontent.com/17773218/61006481-a3487e80-a327-11e9-9e05-b2393cd2088a.png)

I'll clean the code a little bit and document it and then I'll upload the changes

**Comment by ianpan870102** [comment]
Looks amazing IMO! Can't wait to update my centaur-tabs package
