### ISSUE TITLE
Changing back the colors

### ISSUE THREAD

**Issue by ItsNilDev** [ema2159/centaur-tabs#159]
When I put my `load-theme` before `(use-package centaur-tabs)`, the colors used in centaur will inherit my theme:
![image](https://user-images.githubusercontent.com/61497342/119263254-8ce1fe00-bbf3-11eb-9905-7ad9956ea516.png)
how can I undo that ? I want them to have the default value which is kind of blue...

**Comment by nebhrajani-a** [comment]
Could you provide your theme and its configuration? A minimal `init.el` would help.

**Comment by ItsNilDev** [comment]
I don't think you will need that but sure: 
```lisp
(use-package doom-themes
  :ensure t
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-gruvbox t))

(use-package centaur-tabs
  :demand
  :config
  (centaur-tabs-mode t))
(setq centaur-tabs-set-icons t)
(setq centaur-tabs-style "wave")
(setq centaur-tabs-height 32)
(setq centaur-tabs-set-bar 'left)

```

**Comment by nebhrajani-a** [comment]
You're using `doom-gruvbox`: the expected behaviour is that centaur-tabs will inherit doom's colors to match. Not all themes are supported, which is why I asked for a minimal config.

 In any case, as mentioned in the README, by customizing the `centaur-tabs-active-bar-face`. Use `M-x customize-face`.

**Comment by ItsNilDev** [comment]
@nebhrajani-a Hey! I think you misunderstand what I want. The thing is that I know how I can customize it but I want some code in my init.el to come and say: "Hey centaur, don't get themed/inherit from my actual theme"

**Comment by ItsNilDev** [comment]
@nebhrajani-a also I don't see any section related to centaur in my doom-gruvbox section? where is it located?

**Comment by nebhrajani-a** [comment]
Unfortunately, I still don't understand what you mean. Other than the active-bar-face, what else do you want to remain unaffected by the theme? Rest assured that those theme-based changes are _useful_, and ones you'll probably want (matching the color of the active tab to the current buffer and inactive ones dimmer, etc).

I'm also not sure what you mean by 'section', which seems to be nonstandard Emacs terminology that I cannot find in the manual. As such, I cannot help.

Furthermore, GitHub issues are specifically for bugs and improvements, and you should *not* consider them a support channel. If that's your use-case, I suggest you ask your questions on the Emacs Reddit, StackExchange, or `#emacs` on `irc.libera.chat`. 

Finally, this issue will remain closed, since your original query (despite the solution being in the README) asked how to change the color of the `active-bar-face` --- note your arrow pointing at the bar --- and was answered.

**Comment by ema2159** [comment]
@ItsNilDev as @nebhrajani-a said you have to customize the `centaur-tabs-active-bar-face`, though there is a catch. You must do so in your configuration after the theme you're using is loaded. This depends on what you're using in your configuration (i.e. use-package).

**Comment by chookity-pokk** [comment]
Related to this, I am unable to get my customization to the active bar face to show. I put it at the end of my config and when looking up the face under `customize-face` it shows the color I've set as apposed to the cyan, but cyan is always displayed. I tried doing `M-:` and running the command to customize the face but I can't get it to change.  Below is the command I'm using,

`(setq centaur-tabs-active-bar-face "#957dad")`
