### ISSUE TITLE
turning on modified marker crashes emacs

### ISSUE THREAD

**Issue by f0uriest** [ema2159/centaur-tabs#20]
basically, with `(setq centaur-tabs-set-modified-marker t)` in my init.el, typing anything into a buffer (ie, modifying it) crashes emacs entirely. Turning off the modified marker seems to fix it.
Emacs version 25.2, centaur-tabs version 20190711.520

**Comment by ema2159** [comment]
Hi! Could you try to change the marker character and see if it works like that?

**Comment by f0uriest** [comment]
It looks like if I select a specific marker it works fine (tried *, o, m), but with the default marker it crashes

**Comment by ema2159** [comment]
Nice, just as I suspected, is probably a unicode support problem. I think probably Emacs 25.2 doesn't support all unicode symbols or something. Another option was the `(make-string)` function but I think that's not the problem because the close button is showing isn't it?

What I offer to you as a solution is to try some other unicode character that looks similar and works for you. You could instead of using the *,o or m character, use the Emacs unicode inserting function an look for a marker that you like!

**Comment by f0uriest** [comment]
Yeah the close button works fine. ASCII characters are fine for me for the modified marker, I don't really need unicode, so I'll mark this as closed. Thanks for the help, I've been looking for a good tab extension for emacs for a while now and I really like this one.
