### ISSUE TITLE
weird text flicker on tabline

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#45]
when using Magit I some times see regular text appear for a split second on the tabline. Can't find reproducible steps yet though.

**Comment by ema2159** [comment]
That's odd, I use Magit all the time and never had this problem. The headerline (and with it the tabs) are disabled by default in Magit buffers

**Comment by andreyorst** [comment]
Some times when I do actions in Magit, text flickers in other's window tabline
![image](https://user-images.githubusercontent.com/19470159/62832481-78f42480-bc37-11e9-8086-a9c54d993680.png)
Could not capture the screenshot yet, it seems random, but this is how windows are arranged on my setup

**Comment by Compro-Prasad** [comment]
The flicker is obvious as the tabs are recalculated everytime redisplay happens. This might be caused because of poor caching or unnecesary updates. I think, there is a lot of code that needs to be fixed. We need to be specific when to update the tabs and when not to update them. This is just a guess though. I don't have flickering issues but the cursor movement is bit glitchy, i.e. skips some lines when doing C-n/C-p when **centaur-tabs** is enabled.

**Comment by ema2159** [comment]
I actually know where it can be improved. It's the `centaur-tabs-after-modifying-buffer` function which redisplays unnecessarily the tabs. It's even in the to do list, but I haven't had the time to check it

**Comment by andreyorst** [comment]
I guess that wasn't text but a tab appeared and disappeared rather quickly. Today I had this tab with really long name appeared because of Treemacs creating such buffer while editing commit message in Magit:

![image](https://user-images.githubusercontent.com/19470159/64601063-ea54fd80-d3c4-11e9-940d-c146d8be7efb.png)

**Comment by mfiano** [comment]
I have noticed this problem for a couple years now, and I still have the issue with the latest version. I tracked it down to the auto-scrolling feature. With `(setq centaur-tabs-auto-scroll-flag nil)` the issue does not occur, but of course I can never see tabs outside of the view. The issue is, that when moving around in a buffer, sometimes the currently active tab will move around in the tab-line, into seemingly random positions. Additionally, this only occurs for the tab-line in some windows, usually the middle split in an equal sized window configuration that looks like:
```
_____________
|   |   |   |
|   |   |   |
‾‾‾‾‾‾‾‾‾‾‾‾‾
```
I therefor think that the scrolling behavior needs some work, and this issue should be re-opened. I don't see anything that would cause weird scrolling artifacts to occur when not switching buffers, but just simply moving the point around in a buffer. This is really bizarre, and has caused me to disable centaur-tabs to manage the tabline. I try it again every few months only to be disappointed.

I do not want this message to come off as a whiny complaint, as I have a lot of respect for @ema2159 and this otherwise wonderful package, as they have helped me in real-time on multiple occasions on the Doom Emacs Discord server. I am a bit sad I still can't bring myself to use this library due to the glitchy active tab flickering, but I want to thank them for all their hard work.
