### ISSUE TITLE
Fundamental mode use same icon active color as tab foreground

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#49]
`recentf` buffer uses `Fundamental` mode, but an icon is used for Emacs Lisp:
![image](https://user-images.githubusercontent.com/19470159/62971983-ba452980-be1b-11e9-831b-be36c0111772.png)
And when this tab is active, the color of the icon is the same as active face:
![image](https://user-images.githubusercontent.com/19470159/62972060-d9dc5200-be1b-11e9-8fe7-924a0f7c74b9.png)
Changing mode fixes the issue.

**Comment by ema2159** [comment]
That has more to do with the icon face from all the icons and the color assigned to that icon in the theme you're using. What theme are you using?

**Comment by andreyorst** [comment]
that's `doom-one` theme I'm using here

**Comment by ema2159** [comment]
I currently maintain `doom-themes`, but the one, one-light and vibrant are Henrik's (hlissner) themes so sadly I'm not allowed to modify them. I'd request a change in `all-the-icons` repo, but that's useless given that that repo has been inactive for quite some time (and it has always been like that). Given that I can't solve this issue here, I'll have to close the issue, but I encourage you to try other doom-themes (since I'm in charge of that repo, Solarized Dark, Gruvbox, Palenight, Moonlight, Fairy Floss, Wilmesdorf and Outrun themes had been added).

**Comment by andreyorst** [comment]
Understandable. No problem :)
