### ISSUE TITLE
Change tabs location

### ISSUE THREAD

**Issue by MYDavoodeh** [ema2159/centaur-tabs#54]
Just read the README and I guess there weren't any feature to change tabs location...
I also didn't find any guide/wiki or issues about this matter so I thought it's fine to open one.
Sorry if it's duplicated...
Some possible options can be: Above status-bar, Below status-bar, top, bottom, and etc...
I think the concept is pretty clear and doesn't need any further explanations.

{Sorry for bad English and not having enough info about how to open issues and stuff}
Thanks for your time and effort!

**Comment by andreyorst** [comment]
Centaur Tabs uses the [header-line](https://www.gnu.org/software/emacs/manual/html_node/elisp/Header-Lines.html) which is displayed on the top. IIUUC you want to display tabs at bottom you'll have to use [mode-line](https://www.gnu.org/software/emacs/manual/html_node/emacs/Mode-Line.html) which is used to display relevant buffer information, like mode, position and other data. To display tabs at the side someone would need to populate buffer with tabs data in a way how [imenu-list](https://github.com/bmag/imenu-list) does this, which is entirely different approach.

I would actually like a beautiful list of buffers in a side bar menu though.

**Comment by ema2159** [comment]
What @andreyorst  says is correct, I'm unable to implement this feature because the use of the `header-line`. I think I've seen a package that uses the mode-line to show tabs with opened buffers but I don't quite remember it's name. If instead you want to display a list of the currently opened buffers at the side of the window, there is `sidebar.el` that has that functionality.
