### ISSUE TITLE
Tab support landed in Emacs master, any plan to support it ?

### ISSUE THREAD

**Issue by jixiuf** [ema2159/centaur-tabs#65]
https://www.reddit.com/r/emacs/comments/dcryg1/tab_support_landed_in_emacs_master/
new variable `tab-line-format`  is added after `origin/feature/tabs` is merged .

I try to    replace all `header-line-format` with `tab-line-format` in centaur-tabs.el,
it seems works

**Comment by Compro-Prasad** [comment]
Thanks for the mention. I will check it out and report for further details in future.

**Comment by ema2159** [comment]
@jixiuf that's pretty cool, I definitely will! But I'll most likely do it the next Emacs release. Meanwhile I'll try to check the documentation

**Comment by ema2159** [comment]
It seems that it works a little bit differently and has a lot of cool features. We have a tab-line which is what will eventually replace the header-line, and the tab-bar which works  more like tabs in VIM (tabs per window configuration). What centaur-tabs can do eventually is:

1 - Configuring the tab-bar and tab-line appearance
2 - Creating smart ways to change between both
3 - Manage groups on the tab-line (which is what it already does with the header-line)

I'm excited because this presents a pretty cool set of new possibilities. Let's hope this presents a pretty nice opportunity to grow this package.
