### ISSUE TITLE
Option to customize `kill-buffer` behavior

### ISSUE THREAD

**Issue by pcr910303** [ema2159/centaur-tabs#79]
`centaur-tabs` adds the function [`centaur-tabs-buffer-track-killed`](https://github.com/ema2159/centaur-tabs/blob/706c6f198803e503dbc1f63ad0fd9a15391474bf/centaur-tabs.el#L1776) to the [`kill-buffer-hook`](https://github.com/ema2159/centaur-tabs/blob/706c6f198803e503dbc1f63ad0fd9a15391474bf/centaur-tabs.el#L1840), which when the current buffer is killed, moves to the next tab.

I find this behavior highly unintuitive (unless all buffers are presented in the tab-bar), so I would like an option to disable this. I think a simple `when` will be enough, I can make a PR for this. I would like to ask: are you not opposed in introducing such option?

**Comment by ema2159** [comment]
You could make a PR to add the functionality that suits you the best, just make sure that the default behaviour remains the same.

By the way, why do you consider it unintuitive? I think that most programs with tabs (browsers, other editors etc) behave exactly the same.

**Comment by pcr910303** [comment]
@ema2159 Well, mostly because I found the mode-based grouping unintuitive, but I've adapted projectile yesterday, so it's really a non-issue for me now.

**Comment by ema2159** [comment]
Awesome! You can always customize the grouping function to suit your needs

**Comment by lgiordani** [comment]
@ema2159 I just found this issue while I was investigating the same problem. I find it counter-intuitive because when I open a tab that is opened on the right of the current tab, but when I close the newly created one I end up in the tab on the right

```
 current tab
 V
TAB1 | TAB2

         current tab
         V
TAB1 | NEWTAB | TAB2 (open a new tab)

        current tab
        V
TAB1 | TAB2 (close tab)
```

So, if I keep opening and closing a tab I will visit all the tabs instead of staying where I am.
I appreciate this is the default behaviour, I'd like to know if it's possible to change that in my configuration, maybe overriding the default function. I'm a complete beginner with EmacsLisp, so can you please provide a quick example on how to do it?

Thanks!
