### ISSUE TITLE
Focused buffer window gets dimmed when using centaur-tabs with auto-dim-other-buffers

### ISSUE THREAD

**Issue by maronin** [ema2159/centaur-tabs#85]
When using centaur-tabs package with [auto-dim-other-buffers](https://github.com/mina86/auto-dim-other-buffers.el), focused window randomly get dimmed.

I am not sure why this happens. Can anyone point me in the right direction to debug this? I really want to use this package combined >.<

Thank you so much!

**Comment by ema2159** [comment]
This is likely because the tabs get focused for a moment when updating the groups. I´m not quite sure how to solve this since auto-dim is a package that seems to have lost its maintenance for quite some time and I personally have never used it.

**Comment by maronin** [comment]
> This is likely because the tabs get focused for a moment when updating the groups. I´m not quite sure how to solve this since auto-dim is a package that seems to have lost its maintenance for quite some time and I personally have never used it.

Thank you for your reply! I will try and look into the update issue.

Also, is there any way to change the tab color based on the currently focused window? That would solve my current issue.

Thanks again! 👍

**Comment by ema2159** [comment]
Is there anyway you can show me like with a gif or something the problem?

**Comment by maronin** [comment]
Sure!

Here's a link to the gif -> https://im7.ezgif.com/tmp/ezgif-7-92cfb63024ed.gif

**Comment by ema2159** [comment]
Damn, the gif expired! I think you can post it directly here if I'm not wrong

**Comment by maronin** [comment]
Sorry, here is link to imgur. The gif was too big to upload here:

https://imgur.com/QTW1Dsq

**Comment by ema2159** [comment]
I'm curious, does that happens also with a modeline packcage? Please show me your config on autodim, I think there's something I can try.

**Comment by maronin** [comment]
![image](https://user-images.githubusercontent.com/1514285/72819566-7d3b5980-3c3b-11ea-8d0c-021c15ae567e.png)

I just used the default settings from: https://github.com/mina86/auto-dim-other-buffers.el

Here they are below:

`(require 'auto-dim-other-buffers)`
`(auto-dim-other-buffers-mode)`
`(add-hook 'after-init-hook (lambda ()`
			     `(when (fboundp 'auto-dim-other-buffers-mode)`
			       `(auto-dim-other-buffers-mode t))))
`

**Comment by ema2159** [comment]
I'm finding it difficult to solve this and given that the auto-dim package doesn't seem to be maintained anymore, I would encourage you to instead start using another thing to highlight the focused buffer from the window. A very good option would be a nice mode-line package like: https://github.com/seagle0128/doom-modeline. You could combine that with a nice theme package that integrates well with both packages (like doom-themes) and you would have something like this:
![screen](https://user-images.githubusercontent.com/17773218/73111256-52693380-3ecf-11ea-9384-085c08a1f2ed.png)

Maybe that would be a better option because it's better to stop using unmaintained packages given that they often present these kind of bugs which will not be solved because there's anybody to do so.

**Comment by maronin** [comment]
Thank you so much for your efforts ema2159! I will check out doom-modeline. 

I will have to agree with you, using outdated packages is probably not a good idea.

I love using your Centaur-Tabs package, you did such a good job on it!!! Keep up the great work. The Emacs world needs more people like yourself! 😄 

Thanks again! 👍

**Comment by ema2159** [comment]
https://github.com/gonewest818/dimmer.el

**Comment by ema2159** [comment]
@maronin hey, can you try this again if you can? I think it was a probably solved when #18 was solved. Also, you can use dimmer.el which is maintained.

**Comment by maronin** [comment]
It works! Thank you so much for your hard work, I will use dimmer.el instead 👍
