### ISSUE TITLE
Feature request: Functions for tabs selection

### ISSUE THREAD

**Issue by ANGkeith** [ema2159/centaur-tabs#92]
Hi, thank you for this package! I've really enjoyed it.

Is it possible to request for a feature (for the tabs to be able to be selected by functions).

ie. I can map the function such that i can access the tabs with 
"C-1" "C-2" ... "C-9"

**Comment by ema2159** [comment]
Hello! Sorry for the late answer. If I'm not wrong, there's a function to do what you want. It's not documented, that's why you didn't find it. I've never used though.
The function in question is `centaur-tabs-select-visible-tab` and you use it by assigning a keybinding that ends with a number for example `(global-set-key (kbd "C-t C-1") 'centaur-tabs-select-visible-tab)`

**Comment by ANGkeith** [comment]
Yes, thank you so much. That's exactly what i am looking for.
