### ISSUE TITLE
Missing dependency: powerline

### ISSUE THREAD

**Issue by Volker-Weissmann** [ema2159/centaur-tabs#94]
centaur-tabs does not work without powerline

You should list powerline as a dependency.

**Comment by ema2159** [comment]
It is listed. For some reason, the package has to be manually added. I wasn't that way before. I'll try to give it a check.

**Comment by Volker-Weissmann** [comment]
Thank you and good luck.

**Comment by ema2159** [comment]
Hi! Could you tell me how to reproduce? I've had this problem before but I'm not sure why now it's not occurring in my system anymore.

**Comment by Volker-Weissmann** [comment]
Remove .emacs.d and put the following into your emacs init file:
```

(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
  ;; and `package-pinned-packages`. Most users will not need or want to do this.
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  )
(package-initialize)
(package-refresh-contents)
(package-install 'use-package)
(use-package centaur-tabs
	     :load-path "/path/to/centaur-tabs")
```

**Comment by ema2159** [comment]
I've installed it from scratch several times using MELPA and straight.el. It sets powerline automatically. Are you using MELPA stable?

**Comment by Volker-Weissmann** [comment]
I'm using the code I posted.

**Comment by ema2159** [comment]
I've done a centaur tabs installation from scratch and it is indeed pulling powerline. It has to since it is listed as a dependency as the following screenshot from MELPA shows:
![image](https://user-images.githubusercontent.com/17773218/89855939-16d54480-db55-11ea-891e-f5af6d630f75.png)
That's why this was quite weird to me.

It may have to do with the way you're loading centaur-tabs, since for some reason the snippet you pasted isn't working. Also, I'm seeing that you're manually loading centaur-tabs by indicating its path, which may indicate that it is not pulling the package from MELPA. That may also be what's happening with powerline.

I'd have to check since I moved away from package.el quite some time ago in favor of straight.el, so I don't remember that well how it worked.

**Comment by ema2159** [comment]
Oh, now I see. Remove the `:load-path "/path/to/centaur-tabs"` part and add `:ensure t` instead.
