### ISSUE TITLE
Conflicting with semantic mode

### ISSUE THREAD

**Issue by WarFox** [ema2159/centaur-tabs#99]
Love this package, it's so beautiful and fast. I'm using this in my Spacemacs setup with a private layer https://github.com/WarFox/spacemacs.d/tree/master/layers/tabs

Works great!

However it's conflicting with `semantic` mode
When using `semantic-stickyfunc-mode` it shows the current function name in the top header line. This is where `centaur-tabs` shows up, so it conflicts. Tabs are not shown, instead the function names are shown.

Have you experienced this?

I've disabled `semantic-stickyfunc-mode` for now, but it'd be nice get them both working.

Is it possible to change the tab position, maybe bring it to bottom instead of on top?

**Comment by ema2159** [comment]
This issue is not quite possible to solve Emacs 26>, since centaur-tabs uses the header-line to render the tabs, and to bring it to the bottom you'd have to use the modeline which is almost always being used. However, in Emacs 27, there's a tabline, which can be used to render the native tabs, but also centaur-tabs! I've been unable to support it yet since I've been busy, however, it's not that difficult to do so I'll try to work on it soon. Which Emacs version are you using in your Spacemacs?

**Comment by WarFox** [comment]
Thank you for replying so fast! 

I’m using 26.3 now. Will switch to 27 when the stable version is released

I didn’t know 27 has native tabs! I can certainly wait. 

I would like to help though. Is there anything that I can help with?

**Comment by ema2159** [comment]
I think we will not be able to for Emacs 26. For Emacs 27 I'm working on it!

**Comment by ema2159** [comment]
Now centaur-tabs uses the tab'line in Emacs 27, so I think this problem shouldn't be happening anymore on that version. For Emacs 26 there's nothing we can do since both packages use the header line. I'll close this issue now, but please tell me (whenever you're able to try Emacs 27) if it behaves as you'd expect!

**Comment by WarFox** [comment]
Thank you for doing this. I just tried it and confirm that it works on both GUI and terminal :tada:
Much appreciated
